# - Try to find LibDMP-library
# Once done this wil define
# LIBDMP-LIBRARY_FOUND
# LIBDMP-LIBRARY_INCLUDE_DIRS
# LIBDMP-LIBRARY_LIBRARIES
# LIBDMP-LIBRARY_DEFINITIONS

find_path(LIBDMP-LIBRARY_INCLUDE_DIR dmp-library.hpp
	HINTS "${CMAKE_CURRENT_SOURCE_DIR}/../libdmp-library/include")

find_library(LIBDMP-LIBRARY_LIBRARY NAMES dmp-library libdmp-library
	HINTS "${CMAKE_CURRENT_BINARY_DIR}/../libdmp-library/src")

message("Current bin dir: ${CMAKE_CURRENT_BINARY_DIR}")
message("Current src dir: ${CMAKE_CURRENT_SOURCE_DIR}")

set(LIBDMP-LIBRARY_LIBRARIES ${LIBDMP-LIBRARY_LIBRARY})
set(LIBDMP-LIBRARY_INCLUDE_DIRS ${LIBDMP-LIBRARY_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBDMP-LIBRARY DEFAULT_MSG
	LIBDMP-LIBRARY_LIBRARY LIBDMP-LIBRARY_INCLUDE_DIR)

if(NOT LIBDMP-LIBRARY_FOUND)
	IF (LIBDMP-LIBRARY_FIND_REQUIRED)
		message(SEND_ERROR "Unable to find dmp-library")
	ENDIF(LIBDMP-LIBRARY_FIND_REQUIRED)
endif(NOT LIBDMP-LIBRARY_FOUND)

mark_as_advanced(LIBDMP-LIBRARY_INCLUDE_DIR LIBDMP-LIBRARY_LIBRARY)
